### ISSUE TITLE
[BUG/ISSUE] Nf_Def_Var_Deflate: can not compress variable : P0

### ISSUE THREAD

**Issue by Zitely** [geoschem/HEMCO#41] opened 2020-07-22 02:17 UTC
## Describe the bug
Right before finishing a HEMCOsa run, the run crashes.

## To Reproduce

**Run commands**
1. I used the attached HEMCO_Config.rc file
2. HEMCO_sa_Time.rc was set for 2011: 
START:   2011-01-01 00:00:00
END:     2011-02-01 00:00:00
3. The rest of the HEMCO_sa files are the default.
4. To run the model I typed ./runHEMCO.sh (this is the default file too)

## Expected behavior
Finish the run successfully and create monthly emission files. No monthly files were created except for one file corresponding to the first month (HEMCO_sa.ek_HH.201101010000.nc). This is interesting because on previous HEMCOsa versions the output files had timestamps corresponding to the ending of each timestep and no starting file was created. This is a quick question: which month does this file corresponds to? 

## Error messages
```
 Calculate emissions at 2011-01-31 23:00:00
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
**Nf_Def_Var_Deflate: can not compress variable : P0**
```

## Required information
Please include the following:
 - HEMCO v3.0.0
 - Compiler version that you are using: gcc version 8.3.0 (Debian 8.3.0-6) 
 - netCDF and netCDF-Fortran library version: netCDF-4 classic model and netcdf library version 4.6.1 
 - Computational environment: cluster

## Files attached

[HEMCO.log](https://github.com/geoschem/HEMCO/files/4957441/HEMCO.log)

[HEMCO_Config.txt](https://github.com/geoschem/HEMCO/files/4957443/HEMCO_Config.txt)

**Comment by lizziel** [comment] 2020-07-22 13:22
Hi @zitely, can you also include the run log? You can generate one by running with:
`./runHEMCO.sh > run.log`

**Comment by Zitely** [comment] 2020-07-22 17:01
Hi Lizzie, 
It was taking to long for the monthy run to finish, so instead I did a quick one day run. I am attaching the new HEMCO.log and the run.log. HEMCO_Config remained the same as before. 

[run.log](https://github.com/geoschem/HEMCO/files/4961361/run.log)
[HEMCO.log](https://github.com/geoschem/HEMCO/files/4961362/HEMCO.log)

Thanks

**Comment by lizziel** [comment] 2020-07-22 17:11
Thanks @Zitely. I have not been able to reproduce your issue and I wonder if it is because we are using different config files. Could you post all of your config files here. Besides HEMCO_Config.rc there should also be the following:
HEMCO_sa_Config.rc
HEMCO_sa_Grid.05x0625.rc
HEMCO_sa_Spec.rc
HEMCO_sa_Time.rc
HEMCO_Diagn.rc

**Comment by Zitely** [comment] 2020-07-22 17:19
Here they go. Thanks Lizzie!
[HEMCO_Diagn.txt](https://github.com/geoschem/HEMCO/files/4961426/HEMCO_Diagn.txt)
[HEMCO_sa_Time.txt](https://github.com/geoschem/HEMCO/files/4961427/HEMCO_sa_Time.txt)
[HEMCO_sa_Spec.txt](https://github.com/geoschem/HEMCO/files/4961428/HEMCO_sa_Spec.txt)
[HEMCO_sa_Grid.05x0625.txt](https://github.com/geoschem/HEMCO/files/4961429/HEMCO_sa_Grid.05x0625.txt)
[HEMCO_sa_Config.txt](https://github.com/geoschem/HEMCO/files/4961430/HEMCO_sa_Config.txt)

**Comment by lizziel** [comment] 2020-07-22 21:46
Observations:
Diagnostic frequency is in both HEMCO_Config.rc (e.g. Monthly) and HEMCO_sa_Config.rc (e.g. 00000001 000000 for daily). Which one is used?

**Regarding the question about filename timestamp:**

> ...on previous HEMCOsa versions the output files had timestamps corresponding to the ending of each timestep and no starting file was created. This is a quick question: which month does this file corresponds to?

HEMCO now uses the averaging period start time not end time by default in HEMCO diagnostic files. This change happened in HEMCO v2.1.001, released as part of GEOS-Chem v11.02d in late 2017. However, using the default is optional. You can configure it in the HEMCO config file with keyword `DiagnTimeStamp`, set to `start`, `mid`, or `end`. If you want to go back to the old method of using the end date then you can change it back this way.

**Regarding the primary issue of failure to compress P0:**
I am still not able to reproduce the issue. Ideally we would be able to see the netcdf error code associated with the problem to get more information. You can get it by adding a print statement to this file:
`src/Shared/NcdfUtil/m_netcdf_io_define.F90`

The code is exiting gracefully in this block:
```
          ! Check for errors.                                                             
          ! No message will be generated if the error is simply that the                  
          ! file is not netCDF-4                                                          
          ! (i.e. netCDF-3 don't support compression)                                     
          IF ( (ierr.ne.NF_NOERR) .and. (ierr.ne.NF_ENOTNC4)) THEN

             ! Errors enabling compression will not halt the program                      
             doStop = .False.

             ! Print error                                                                
             err_msg = 'Nf_Def_Var_Deflate: can not compress variable : '// Trim (name)
             CALL Do_Err_Out (err_msg, doStop, 0, 0, 0, 0, 0.0d0, 0.0d0)
          END IF
```

Try adding this print statement prior to the call to Do_Err_Out
`print *, "Nf_Def_Var_Deflate error code: ", ierr`

Then recompile in the build directory, checking afterwards that the new executable was successfully copied to the run directory by looking at the file timestamp. You should not need a new run directory.
```
make -j
make install
```

The variable `P0`, a scalar, is included in all output files so it should be sufficient to do a 1-hr run and change the diagnostic frequency to 1-hour in `HEMCO_sa_Config.rc` to ensure an attempt to write output. Report back here with the error code.

**Comment by Zitely** [comment] 2020-07-22 22:05
Here it is:

 Nf_Def_Var_Deflate error code:          -36

**Comment by lizziel** [comment] 2020-07-22 22:28
Thanks! Error code -36 corresponds to an [Invalid argument error](https://www.unidata.ucar.edu/software/netcdf/docs/nc-error-codes.html). It is listed as a NetCDF-3 error code, but it is also applicable to NetCDF-4. 

The next step would be to check if one of arguments passed to `nf_def_var_deflate` is not okay. You can try printing each of them out in the same place you added a print before, and then inspect if anything obviously is wrong.

Alternatively, if compression is not a needed feature and you need to a quick fix, you can rebuild with output compression turned off. To do this you need to go into file CMakeLists.txt located in the top-level HEMCO directory. Comment out these lines:
```
#---------------------------------------------------------------------
# Use the NC_HAS_COMPRESSION def if nf_def_var_deflate is in netcdf.inc
#---------------------------------------------------------------------
if(EXISTS ${NETCDF_F77_INCLUDE_DIR}/netcdf.inc)
    file(READ ${NETCDF_F77_INCLUDE_DIR}/netcdf.inc NCINC)
    if("${NCINC}" MATCHES ".*nf_def_var_deflate.*")
        target_compile_definitions(HEMCOBuildProperties
            INTERFACE "NC_HAS_COMPRESSION"
        )
    endif()
endif()
```

Then recompile from scratch:
```
cd build
rm -rf *
cmake ../CodeDir
make -j make install
```

**Comment by Zitely** [comment] 2020-07-22 23:13
It worked Lizzie! The run ended without showing errors.

Many thanks.

**Closed** 2020-07-22 23:14 UTC
Labels: bug
